apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: streaming-service
  namespace: highload
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: streaming-service
  namespaceSelector:
    matchNames:
      - highload
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
