apiVersion: v1
kind: ConfigMap
metadata:
  name: streaming-service-config
  namespace: highload
data:
  LISTEN_ADDR: ":8080"
  REDIS_ADDR: "redis-master:6379"
  WINDOW_SIZE: "50"
  Z_THRESHOLD: "2.0"
  QUEUE_SIZE: "10000"
